home_page:
    pattern:  /
    defaults: { _controller: SkimiaProjectManagerBundle:Home:home }
    
entity_generate:
    pattern: /generator/entity/{id}
    defaults: { _controller: SkimiaProjectManagerBundle:Generator:entity }
