parameters:
#    skimia_project_manager.example.class: Skimia\ProjectManagerBundle\Example

services:
#    skimia_project_manager.example:
#        class: %skimia_project_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    spm.generator:
        class: Skimia\ProjectManagerBundle\Service\Generator
        arguments: ["@templating"]
    spm.beautifier:
        class: Skimia\ProjectManagerBundle\Service\Beautifier
    spm.twig.word_transformer_extension:
        class: Skimia\ProjectManagerBundle\Twig\WordTransformerExtension
        tags:
            - { name: twig.extension }

    spm.registration.listener:
        class: Skimia\ProjectManagerBundle\EventListener\RegisterListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

    spm.registration.form.type:
        class: Skimia\ProjectManagerBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: spm_registration }
        