    #####################
    ### ANNOUNCEMENTS ###
    #####################
 
spm_announcement_list:
    pattern: /announcement
    controller: "SPM.Announcement.ListController" 
    view: "@SkimiaProjectManagerBundle:Announcement:list.html.twig"
    title: "Annonces"

spm_announcement_create:
    pattern: /announcement/new
    controller: "SPM.Announcement.CreateController" 
    view: "@SkimiaProjectManagerBundle:Announcement:form.html.twig"
    title: "Créer une Annonce"
    
spm_announcement_show:
    pattern: /announcement/:announcementId
    controller: "SPM.Announcement.ShowController" 
    view: "@SkimiaProjectManagerBundle:Announcement:show.html.twig"
    title: "Annonce"
    
spm_announcement_edit:
    pattern: /announcement/:announcementId/edit
    controller: "SPM.Announcement.EditController" 
    view: "@SkimiaProjectManagerBundle:Announcement:form.html.twig"
    title: "Editer une Annonce"
    
spm_announcement_delete:
    pattern: /announcement/:announcementId/delete
    controller: "SPM.Announcement.DeleteController" 
    view: "@SkimiaProjectManagerBundle:Announcement:show.html.twig"
    title: "Annonces"
