    #####################
    ### ANNOUNCEMENTS ###
    #####################
 
spm_announcement_list:
    pattern: /announcement
    controller: "Announcement.ListController" 
    view: "@SkimiaProjectManagerBundle:Announcement:list.html.twig"
    title: "Annonces"

spm_announcement_create:
    pattern: /announcement/new
    controller: "Announcement.CreateController" 
    view: "@SkimiaProjectManagerBundle:Announcement:form.html.twig"
    title: "Créer une Annonce"
    
spm_announcement_edit:
    pattern: /announcement/:announcementId/edit
    controller: "Announcement.EditController" 
    view: "@SkimiaProjectManagerBundle:Announcement:edit.html.twig"
    title: "Editer une Annonce"
    
spm_announcement_delete:
    pattern: /announcement/:announcementId/delete
    controller: "Announcement.DeleteController" 
    view: "@SkimiaProjectManagerBundle:Announcement:show.html.twig"
    title: "Annonces"
