    #####################
    ### ENTITY
    #####################
 
spm_entity_list:
    pattern: /entity
    controller: "SPM.Entity.ListController" 
    view: "@SkimiaProjectManagerBundle:Entity:list.html.twig"
    title: "LIST Entity"

spm_entity_create:
    pattern: /entity/new
    controller: "SPM.Entity.CreateController" 
    view: "@SkimiaProjectManagerBundle:Entity:form.html.twig"
    title: "CREATE Entity"
    
spm_entity_show:
    pattern: /entity/:Id
    controller: "SPM.Entity.ShowController" 
    view: "@SkimiaProjectManagerBundle:Entity:show.html.twig"
    title: "SHOW Entity "
    
spm_entity_edit:
    pattern: /entity/:Id/edit
    controller: "SPM.Entity.EditController" 
    view: "@SkimiaProjectManagerBundle:Entity:form.html.twig"
    title: "EDIT Entity"
    
spm_entity_delete:
    pattern: /entity/:Id/delete
    controller: "SPM.Entity.DeleteController" 
    view: "@SkimiaProjectManagerBundle:Entity:show.html.twig"
    title: "DELETE Entity"
