    #####################
    ### FIELD
    #####################
 
spm_bundle_show_bundle_entity_show_field_list:
    pattern: /field
    controller: "Field.ListController" 
    view: "@SkimiaProjectManagerBundle:Field:list.html.twig"
    title: "LIST Field"

spm_bundle_show_bundle_entity_show_field_create:
    pattern: /field/new
    controller: "Field.CreateController" 
    view: "@SkimiaProjectManagerBundle:Field:form.html.twig"
    title: "CREATE Field"
    
spm_bundle_show_bundle_entity_show_field_show:
    pattern: /field/:fieldId
    controller: "Field.ShowController" 
    view: "@SkimiaProjectManagerBundle:Field:show.html.twig"
    title: "SHOW Field "
    
spm_bundle_show_bundle_entity_show_field_edit:
    pattern: /field/:fieldId/edit
    controller: "Field.EditController" 
    view: "@SkimiaProjectManagerBundle:Field:form.html.twig"
    title: "EDIT Field"
    
spm_bundle_show_bundle_entity_show_field_delete:
    pattern: /field/:fieldId/delete
    controller: "Field.DeleteController" 
    view: "@SkimiaProjectManagerBundle:Field:show.html.twig"
    title: "DELETE Field"
