    #####################
    ### FIELD
    #####################
 
spm_field_list:
    pattern: /field
    controller: "SPM.Field.ListController" 
    view: "@SkimiaProjectManagerBundle:Field:list.html.twig"
    title: "LIST Field"

spm_field_create:
    pattern: /field/new
    controller: "SPM.Field.CreateController" 
    view: "@SkimiaProjectManagerBundle:Field:form.html.twig"
    title: "CREATE Field"
    
spm_field_show:
    pattern: /field/:Id
    controller: "SPM.Field.ShowController" 
    view: "@SkimiaProjectManagerBundle:Field:show.html.twig"
    title: "SHOW Field "
    
spm_field_edit:
    pattern: /field/:Id/edit
    controller: "SPM.Field.EditController" 
    view: "@SkimiaProjectManagerBundle:Field:form.html.twig"
    title: "EDIT Field"
    
spm_field_delete:
    pattern: /field/:Id/delete
    controller: "SPM.Field.DeleteController" 
    view: "@SkimiaProjectManagerBundle:Field:show.html.twig"
    title: "DELETE Field"
