
spm_homepage:
    pattern: /home
    controller: "SPM.Home.IndexController" 
    view: "@SkimiaProjectManagerBundle:Home:index.html.twig"
    title: "Accueil"
spm_about:
    pattern: /about
    controller: "SPM.Home.AboutController"
    view: "@SkimiaProjectManagerBundle:Home:about.html.twig"
    title: "A propos"