
spm_homepage:
    pattern: /home
    controller: "Home.IndexController" 
    view: "@SkimiaProjectManagerBundle:Home:index.html.twig"
    title: "Accueil"
spm_about:
    pattern: /about
    controller: "Home.AboutController"
    view: "@SkimiaProjectManagerBundle:Home:about.html.twig"
    title: "A propos"

spm_beta:
    pattern: "/beta/:betaKey"
    controller: "Home.BetaController"
    view: "@SkimiaProjectManagerBundle:Home:beta.html.twig"
    title: "Inscription à la bêta"