    #####################
    ### RELATION
    #####################

spm_bundle_show_entity_show_relation_create:
    pattern: /relation/new
    controller: "Relation.CreateController" 
    view: "@SkimiaProjectManagerBundle:Relation:form.html.twig"
    title: "CREATE Relation"
    
spm_bundle_show_entity_show_relation_edit:
    pattern: /relation/:relationId/edit
    controller: "Relation.EditController" 
    view: "@SkimiaProjectManagerBundle:Relation:edit.html.twig"
    title: "EDIT Relation"
    
spm_bundle_show_entity_show_relation_delete:
    pattern: /relation/:relationId/delete
    controller: "Relation.DeleteController" 
    view: "@SkimiaProjectManagerBundle:Relation:show.html.twig"
    title: "DELETE Relation"
