<?php

namespace Skimia\ProjectManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('posted' => 'DESC'));
    }
}
