<?php

namespace Skimia\ProjectManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntityPMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityPMRepository extends EntityRepository
{
    public function getByBundle($bundle){
        return $this->findBy(array(
            'bundle' => $bundle
        ));
    }
}
