<?php

namespace Skimia\ProjectManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
    public function findByUser(User $user)
    {
        $add = '';
        foreach ($user->getGroups() as $group) {
            $add .= ' OR g.id = '.$group->getId();
        }
        $query = $this->createQueryBuilder('g')
                ->where('g.openned = true OR g.public = true'.$add);
        return $this->getEntityManager()->createQuery($query->getDQL())->getResult();
    }
}
